trigger: none
#- master

pool: Hosted Windows 2019 with VS2019 

# variables:
# - group: glance-prod

stages:
 build:
        
  steps:
  - script: |


          echo "testing build"

         # docker build -t  glance:$(Build.Buildnumber) .

    displayName: 'build'

 deploy:
  steps:
  - script: |
  
     echo "testing deployment"    
    displayName: 'deployment'
   
 