trigger: none
#- master

pool: Hosted Windows 2019 with VS2019 

# variables:
# - group: glance-prod

stages:
 stage: dev
        
  steps:
  - script: |


          echo "testing build"

         # docker build -t  glance:$(Build.Buildnumber) .

    displayName: 'build'

 stage: QA      
  steps:

  - script: |

  
     echo "testing deployment"    
    displayName: 'deployment'
   
 